### ISSUE TITLE
aw and bw

### ISSUE THREAD

**Issue by lifeodyssey** [BrandonSmithJ/band-adjustment#1]
Hi, thank you for providing the code of band shifting.

But I found it seems when you do the forward estimation from IOP, you do not add absorption and backscattering of water.

Could you please check your code again?

**Comment by BrandonSmithJ** [comment]
Hi, sorry for the delayed response. While you are correct about aw & bw, as well as the issue with acd (mentioned in your email), I found that correcting these issues actually makes the estimates worse. The problem, I believe, lies in the inconsistent terminology used within the QAA papers. Compare the two papers reference within Mélin & Sclep for QAA & QAAv5:

https://www.researchgate.net/publication/11140186_Deriving_Inherent_Optical_Properties_from_Water_Color_a_Multiband_Quasi-Analytical_Algorithm_for_Optically_Deep_Waters
http://www.ioccg.org/groups/Software_OCA/QAA_v5.pdf

Step 9 in the first paper and Eq. (4) in the second both define the same equations, but refer to the parameters as a_g, and a_dg, respectively. Given QAAv5 is an update, I'm inclined to go with their definition of it containing both detritus and gelbstoff. 

As I said however, this pretty significantly degrades performance of that band adjustment method; I've created a new branch "MS_fixes" which shows this. It has been awhile since I worked with these equations and so I could very well be missing something - take a look, and let me know if you see something.

**Comment by BrandonSmithJ** [comment]
Hi, you are correct about both the aw / bw issue, as well about the acd issue referenced in your email. I've now corrected both of those issues, and updated the repository; the M&S method is slightly improved from before. Thanks for pointing out these problems, and let me know if you notice anything else.
